all:
	nohup python3 xgboost_hyper_Py_2.py
	nohup python3 xgboost_hyper_Py_3.py
	nohup python3 xgboost_hyper_Py_4.py
	nohup python3 xgboost_hyper_Py_5.py
	nohup python3 xgboost_hyper_Py_6.py
	nohup python3 xgboost_hyper_Py_7.py
	nohup python3 xgboost_hyper_Py_8.py
	nohup python3 xgboost_hyper_Py_9.py
